# Generated by Django 3.2 on 2021-05-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210512_0747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospitals2',
        ),
    ]
