# Generated by Django 3.2 on 2021-05-12 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_hospitals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Goal', models.CharField(choices=[('Lose Weight', 'Lose Weight'), ('Maintain', 'Maintain'), ('Build Muscle', 'Build Muscle')], max_length=50)),
                ('units', models.CharField(choices=[('U.S.Stanndard', 'U.S.Stanndard'), ('Metric', 'Metric')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('height_feet', models.IntegerField()),
                ('height_inch', models.IntegerField()),
                ('weight', models.FloatField()),
                ('Age', models.IntegerField()),
                ('Bodyfat', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('Activity_level', models.CharField(choices=[('Lightly Active', 'Lightly Active'), ('Moderately Active', 'Moderately Active'), ('Highly Active', 'Highly Active'), ('Extremely Active', 'Extremely Active')], max_length=50)),
                ('Primary_Diet', models.CharField(choices=[('Anything', 'Anything'), ('Paleo', 'Paleo'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Ketogenic', 'Ketogenic'), ('Mediterranean', 'Mediterranean')], max_length=50)),
                ('Address_Door_number', models.DateTimeField()),
                ('Address_Street', models.CharField(max_length=100)),
                ('Address_town', models.CharField(max_length=100)),
                ('Address_City', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
