# Generated by Django 3.2 on 2021-05-13 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('City', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('Location', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Gym', 'Gym'), ('Hospital', 'Hospital'), ('Yoga Center', 'Yoga Center'), ('Fitness Studios', 'Fitness Studios'), ('Wellness Center', 'Wellness Center'), ('Nutritionists', 'Nutritionists'), ('Physiotherapy Center', 'Physiotherapy Center')], max_length=50)),
                ('Fitness_photo', models.ImageField(upload_to='Fitness-img')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
