# Generated by Django 3.2 on 2021-05-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210512_2307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactus2',
        ),
    ]
