# Generated by Django 3.2 on 2021-05-13 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Zipcode', models.IntegerField(max_length=6)),
                ('Name_on_Card', models.CharField(max_length=200)),
                ('Card_Number', models.IntegerField(max_length=16)),
                ('Exp_Month', models.CharField(max_length=12)),
                ('Exp_Year', models.IntegerField(max_length=4)),
                ('Cvv', models.IntegerField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
