# Generated by Django 3.2 on 2021-05-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_fitnesscenter_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Address_City',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Address_Door_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Address_Street',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Address_town',
        ),
    ]
