# Generated by Django 3.2 on 2021-05-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210518_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slot', models.CharField(choices=[('9Am to 12Pm', '9Am to 12Pm'), ('12Pm to 3Pm', '12Pm to 3Pm'), ('3Pm to 6Pm', '3Pm to 6Pm'), ('6Pm to 9Pm', '6Pm to 9Pm')], max_length=35)),
                ('date', models.DateField()),
                ('phone', models.IntegerField()),
                ('Doctor_specialization', models.CharField(choices=[('cardiologist', 'cardiologist'), ('General Physician', 'General Physician'), ('allergist', 'allergist'), ('anesthesiologist', 'anesthesiologist'), ('dentist', 'dentist'), ('dermatologist', 'dermatologist'), ('fertility specialist', 'fertility specialist'), ('massage therapist', 'massage therapist'), ('neurologist', 'neurologist'), ('pediatrician', 'pediatrician'), ('radiologist', 'radiologist')], max_length=35)),
            ],
        ),
        migrations.AlterField(
            model_name='doctorname',
            name='specialisation',
            field=models.CharField(choices=[('cardiologist', 'cardiologist'), ('General Physician', 'General Physician'), ('allergist', 'allergist'), ('anesthesiologist', 'anesthesiologist'), ('dentist', 'dentist'), ('dermatologist', 'dermatologist'), ('fertility specialist', 'fertility specialist'), ('massage therapist', 'massage therapist'), ('neurologist', 'neurologist'), ('pediatrician', 'pediatrician'), ('radiologist', 'radiologist')], max_length=35),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specialisation',
            field=models.CharField(choices=[('cardiologist', 'cardiologist'), ('General Physician', 'General Physician'), ('allergist', 'allergist'), ('anesthesiologist', 'anesthesiologist'), ('dentist', 'dentist'), ('dermatologist', 'dermatologist'), ('fertility specialist', 'fertility specialist'), ('massage therapist', 'massage therapist'), ('neurologist', 'neurologist'), ('pediatrician', 'pediatrician'), ('radiologist', 'radiologist')], max_length=35),
        ),
    ]
