# Generated by Django 3.2 on 2021-05-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210518_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='Google_meet',
            field=models.TextField(default=''),
        ),
    ]
